version: "3.7"
services:

  app:
    image: "app"
    depends_on:
      - db
    build:
        context: .
        dockerfile: Dockerfile

  db:
    container_name: "postgres_db"
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: admin
      POSTGRES_DB: db

    ports:
      - "5432:5432"
